version: '3'
services:
  frontend:
    image: docker-react-image:latest
    build:
      context: "C:/Users/Youcode/Youcode Project/AlloMediaGroup-SiteVitrine"  
    ports:
      - "5180:5173"  
    depends_on:
      - backend  

  backend:
    image: backendimg:latest
    build:
      context: C:\Users\Youcode\Youcode Project\AlloMediaGroup 
    ports:
      - "3000:8000" 
    environment:
      - NODE_ENV=development
      - DB_HOST=db


